Throw not exceptions, but return thy failures in peace.” - FP preacher

Try<Long> horrorFP(Data payload) { // vavr.Try = specialized Either<Result,Exception>
  return process(payload)
    .onSuccess(e -> log.info(e))
    .flatMap(repo::save)
    .andThen(id -> audit(payload));
}

Try<String> process(Data payload) {
  if (payload.name().isBlank())
    return Try.failure(new Ex("…"));
  return Try.success(payload.name() + "!");
} 

// rewrite the above 2 functions throwing (runtime) exceptions
